version: "3.8"

services:
  wolftime-spinner:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount the CSV file so data persists between container restarts
      - ./standup_scoreboard.csv:/app/standup_scoreboard.csv
    environment:
      - NODE_ENV=production
      - PASSPHRASE=${PASSPHRASE:-wolftime2024}
      - PORT=${PORT:-3000}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
